<div data-block="dropdown" class="minicart-wrapper-test">
     <p><a href="#" class="action" data-trigger="trigger">size guide</a></p>
</div>
<div class="block block-minicart"
     data-mage-init='{
        "dropdownDialog": {
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "timeout": 2000,
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "autoOpen": false,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": []
        }
     }'>
    <div id="minicart-content-wrapper">
       <?php 
          echo $block->getLayout()->createBlock("Magento\Cms\Block\Block")
                                    ->setBlockId("size-guide")->toHtml();
       ?>
    </div>
</div>